### ISSUE TITLE
easier fetching?

### ISSUE THREAD

**Issue by joshhighet** [jjsantanna/aggregator_crawlers_lists_ransomware_groups_leaksites#1]
in lieu of parsing markdown you may find it easier to just leverage the files that generate them, http://ransomwhat.telemetry.ltd/posts & http://ransomwhat.telemetry.ltd/groups

https://github.com/jjsantanna/aggregator_crawlers_lists_ransomware_groups_leaksites/blob/d6325bef12cb545a8fd1b6dd586bf7f83e44c90d/aggregator_crawlers_lists_ransomware_groups.ipynb?short_path=920f89f#L364-L368

**Comment by jjsantanna** [comment]
Dear @joshhighet, thanks for pointing it out! on top of that, thanks for your effort in the collection. I've fixed the code as you suggested. Only one issue, "http://ransomwhat.telemetry.ltd/groups" gives an error when I try to fetch it directly as a pandas dataframe. Later I noticed that it points to https://raw.githubusercontent.com/joshhighet/ransomwatch/main/groups.json. After that, it worked as a charm!

I'm a researcher. and I would like to collaborate with you. Please send me a direct email j.j.santanna@utwente.nl if you have interest.
